Models/Brand.cs
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace Casestudy.Models
{
    public class Brand
    {
        public Brand()
        {
            Products = new HashSet<Product>();
        }

        [Key]
        [DatabaseGenerated(DatabaseGeneratedOption.Identity)]
        public int Id { get; set; }
        [Required]
        [StringLength(200)]
        public string Name { get; set; }
        public virtual ICollection<Product> Products { get; set; }
    }
}

ViewModels/BrandViewModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.ComponentModel.DataAnnotations;
using Casestudy.Models;
using Microsoft.AspNetCore.Mvc.Rendering;
namespace Casestudy.ViewModels
{
    public class BrandViewModel
    {
        private List<Brand> _brands;
        [Required]
        public int Qty { get; set; }
        public string Id { get; set; }
        public string BrandName { get; set; }
        public int BrandId { get; set; }
        public IEnumerable<SelectListItem> GetBrands()
        {
            return _brands.Select(brand => new SelectListItem
            {
                Text = brand.Name,
                Value = Convert.ToString(brand.Id)
            });
        }
        public void SetBrands(List<Brand> brnds)
        {
            _brands = brnds;
        }
    }
}

Controllers/BrandController.cs
using Microsoft.AspNetCore.Mvc;
using Casestudy.Models;
using Casestudy.Utils;
using Casestudy.ViewModels;
using Microsoft.AspNetCore.Http;
using System.Collections.Generic;
using System;
namespace Casestudy.Controllers
{
    public class BrandController : Controller
    {
        AppDbContext _db;
        public BrandController(AppDbContext context)
        {
            _db = context;
        }
        public IActionResult Index()
        {
            BrandViewModel vm = new BrandViewModel();
            // only build the catalogue once
            if (HttpContext.Session.Get<List<Brand>>(SessionVars.Brands) == null)
            {
                try
                {
                    BrandModel brandModel = new BrandModel(_db);
                    // now load the categories
                    List<Brand> brands = brandModel.GetAll();
                    HttpContext.Session.Set<List<Brand>>(SessionVars.Brands, brands);
                    vm.SetBrands(brands);
                }
                catch (Exception ex)
                {
                    ViewBag.Message = "Catalogue Problem - " + ex.Message;
                }
            }
            else
            {
                vm.SetBrands(HttpContext.Session.Get<List<Brand>>(SessionVars.Brands));
            }
            return View(vm);
        }
        public IActionResult SelectBrand(BrandViewModel vm)
        {
            BrandModel brandModel = new BrandModel(_db);
            ProductModel productModel = new ProductModel(_db);
            List<Product> products = productModel.GetAllByBrand(vm.BrandId);
            List<ProductViewModel> vms = new List<ProductViewModel>();
            if (products.Count > 0)
            {
                foreach (Product product in products)
                {
                    ProductViewModel mvm = new ProductViewModel();
                    mvm.Qty = 0;
                    mvm.QtyOnHand = product.QtyOnHand;
                    mvm.QtyOnBackOrder = product.QtyOnBackOrder;
                    mvm.BrandId = product.BrandId;
                    mvm.BrandName = brandModel.GetName(product.BrandId);
                    mvm.Description = product.Description;
                    mvm.Id = product.Id;
                    mvm.CostPrice = Convert.ToDecimal(product.CostPrice);
                    mvm.GraphicName = product.GraphicName;
                    mvm.MSRP = Convert.ToDecimal(product.MSRP);
                    mvm.ProductName = product.ProductName;
                    vms.Add(mvm);
                }
                ProductViewModel[] myProducts = vms.ToArray();
                HttpContext.Session.Set<ProductViewModel[]>(SessionVars.Products, myProducts);
            }
            vm.SetBrands(HttpContext.Session.Get<List<Brand>>(SessionVars.Brands));
            return View("Index", vm); // need the original Index View here
        }
        [HttpPost]
        public ActionResult SelectProduct(BrandViewModel vm)
        {
            Dictionary<string, object> cart;
            if (HttpContext.Session.Get<Dictionary<string, Object>>(SessionVars.Cart) == null)
            {
                cart = new Dictionary<string, object>();
            }
            else
            {
                cart = HttpContext.Session.Get<Dictionary<string, object>>(SessionVars.Cart);
            }
            ProductViewModel[] products = HttpContext.Session.Get<ProductViewModel[]>(SessionVars.Products);
            String retMsg = "";
            foreach (ProductViewModel product in products)
            {
                if (product.Id.Equals(vm.Id))
                {
                    if (vm.Qty > 0) // update only selected item
                    {
                        product.Qty = vm.Qty;
                        retMsg = vm.Qty + " - item(s) Added!";
                        cart[product.Id] = product;
                    }
                    else
                    {
                        product.Qty = 0;
                        cart.Remove(product.Id);
                        retMsg = "item(s) Removed!";
                    }
                    vm.BrandId = product.BrandId;
                    break;
                }
            }
            ViewBag.AddMessage = retMsg;
            HttpContext.Session.Set<Dictionary<string, Object>>(SessionVars.Cart, cart);
            vm.SetBrands(HttpContext.Session.Get<List<Brand>>(SessionVars.Brands));
            return PartialView("AddToCartPartial");
        }
    }
}

Views/Brand/AddToCartPartial.cshtml
@ViewBag.AddMessage

Views/Brand/Index.cshtml
@model BrandViewModel
@{
    ViewData["Title"] = "Index";
    Layout = "~/Views/_Layout.cshtml";
}
<div class="col-sm-2 col-xs-12">&nbsp;</div>
<div class="text-center col-sm-8 col-xs-12">
    <form asp-controller="Brand" asp-action="SelectBrand" method="post">
        <div class="col-sm-4 col-xs-12">&nbsp;</div>
        <div class="col-sm-4 col-xs-12" style="padding-bottom:5%;">
            <span class="col-xs-12">
                <img src="/img/logo.png" />
            </span>
            <span style="font-size:large;top:20px;position:relative;padding:5px;">Brands</span>
            <select asp-for="BrandId" asp-items="@Model.GetBrands()"
                    style="top:35px;position:relative;padding:5px;"
                    class="form-group form-control" onchange="this.form.submit();">
                <option selected style="display:none;">Select Brand</option>
            </select>
        </div>
        <div class="col-sm-4 col-xs-12">&nbsp;</div>
        <catalogue brand="@Model.BrandId"></catalogue>
    </form>
</div>
<div class="modal" id="details_popup">
    <div class="modal-dialog">
        <div class="modal-content col-xs-12" style="background-color:lightskyblue;">
            <div class="modal-body">
                <a href="" style="font-size:xx-large" data-dismiss="modal" class="pullright">X</a>
                <div class="text-center">
                    <img alt="" id="detailsGraphic" height="250" width="300" /><br />
                    <h4 id="prodName"></h4>
                    <h5 id="description"></h5>
                </div>
                <form id="brandsForm" asp-controller="Brand" asp-action="SelectProduct" method="post" role="form">
                    <div class="text-center col-sm-offset-2">
                        <table>
                            <tr>
                                <td class="col-xs-8 text-right">Price</td>
                                <td class="col-xs-4 text-left" id="price"></td>
                            </tr>
                            <tr>
                                <td class="col-xs-6 text-right">Qty:</td>
                                <td class="col-xs-4 text-left">
                                    <input asp-for="Qty" type="number" maxlength="3" size="3" style="width: 50px;" id="qty" />
                                    <input asp-for="Id" type="hidden" id="detailsId" />
                                </td>
                            </tr>
                            <tr><td colspan="2">&nbsp;</td></tr>
                        </table>
                    </div>
                    <div class="text-center">
                        <button type="submit" class="btn btn-sm btn-default" id="modalbtn">
                            Add To Cart
                        </button>
                        <button id="btnRemove" type="submit" class="btn-sm btn btn-danger">Remove Item</button>
                        <a href="/Cart" class="btn btn-sm btn-success">View Cart</a>
                    </div>
                </form>
            </div>
            <div class="modal-footer">
                <div id="results" class="text-center">
                    @ViewBag.AddMessage
                </div>
            </div>
        </div><!--modal-content-->
    </div><!--modal-dialog-->
</div><!--modal-->